python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012Jan7_19fbOldMatchOldTrig $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012c_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /afs/cern.ch/work/m/manzoni/public/DiTau2012Sep17_10fb_v2 $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012c_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012Oct24_12fb_recoilNew $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012c_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTau2012Oct18_12fb_rawMET52 $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012c_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012Sep17_10fb_v2 $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012c_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTau2012June5_5_1fb_nominal_2012WJets $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June5_5_1fb_plateauup $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June5_5_1fb_isoChooseDiLepton $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June5_5_1fb_nominal $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June5_5_1fb_plateaudown $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June5_5_1fb_downslope $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTau2012June5_2_86fb $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTau2012June1_2_86fb $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June1v3_1_6fb $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTau2012June1_1_6fb $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_2012_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTauV520May24_1fbNew $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTauV520May29_1fb $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTauV520May22_1fbSel $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py /tmp/hinzmann/DiTauV520May18_1fbTTsmall $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTauApr18_1fb $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTauApr27_2012L1 $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau.py ~/workspace/ditau/DiTauApr27_noTrig $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
#python -i plot_H2TauTauDataMC_diTau_visMass.py ~/workspace/ditau/DiTauApr11 $CMSSW_BASE/src/CMGTools/H2TauTau/Colin/test_diTau_cfg.py -H visMass
